baseurl = "https://gruneo.de/"
languageCode = "en-us"
title = "Gruneo"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Alicia Ferrer"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Gruneo"

	[params.navigation.links]
		about = "About"
		services= "Services"
		portfolio = "Portfolio"
		contact = "Contact"

	# Hero section
	[params.hero]
		slogan = "Garden in a box"
		subtitle = "Have you ever dreamed of growing your own organic food at home?"
		buttonText = "Find out more"

	# About section
	[params.about]
		headline = "We want to promote urban gardening as a healthier and more conscious way of eating."
		description = "Find your perfect garden box: - Salad Garden: Cherry + Lettuce + Arugula - Herb Garden: Basil + Mint + Cilantro  - Superfood Garden: Microgreens + Chives + Kale"
		#buttonText  =

	# Service section
	[params.services]
		headline = "What Grüneo is about"

		[[params.services.list]]
			icon = "fa-utensils"
			#title =
			description = "Pure fresh veggies & herbs sowed, grew and harvested by you. Be ready for such an authentic taste!"

		[[params.services.list]]
			icon = "fa-leaf"
			#title =
			description = "Introducing sustainable habits in our life & contribute positively to our health"

		[[params.services.list]]
			icon = "fa-home"
			#title =
			description = "Going back to roots and to traditions while living immersed in the agile rhythm of a big city"

		[[params.services.list]]
			icon = "fa-globe-americas"
			#title =
			description = "100% natural products, free of chemicals"

	# Portfolio modals
	[params.portfolio.modal]
		client = "Client"
		date = "Date"
		category = "Category"
		buttonText = "Close"

	# 	# Aside section
	# [params.aside]
	# 	headline = "Get the Creative Theme for Hugo"

	# [params.aside.button]
	# 	text = "Download now"
	# 	link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+49 (0) 17626173814"
		email = "hello.gruneo@gmail.com"
		instagram = "https://instagram.com/gruneobox/"

	# Google Maps section
	# [params.location]
	#  latitude  = "34.007850"
	#  longitude = "-118.499305"
	#  maps_api_key = ""